### ISSUE TITLE
add a photo trait to the ontology

### ISSUE THREAD

**Issue by bellerbrock** [Planteome/ibp-sweetpotato-traits#1]
The sweetpotato breeding program at NCSU takes photos using the fieldbook app, along with traits currently in the ontology. Should a photo trait be considered part of the ontology?

**Comment by bauchetg** [comment]
We have the exact same question pending in the banana ontology. 
Several "photograph traits" were recently created in the Trait dictionary (not finalized yet) , ex:
"Off-type photograph", "Shooting photograph", "Bunch at harvest photograph" and potentially a  photograph could be taken for anything... 
Is there a way a photograph could be linked to an existing cvterm/ontology trait? Like a Dbxrefs?
Suggestions are very welcome.

**Comment by elizabetharnaud** [comment]
In fact, the use of photos to describe the traits is common process for the genebanks characterization trials and  to determine the off-types-  I am less convinced that traditional breeders use photos on their evaluation trials but this can apply in the scope of the phenotyping with sensors. There are 2 types of photos in my view: 
1. Reference photos that illustrates a trait: the Crop Ontology web tool enables the display of a photo in the attribute information that illustrates the trait or the symptoms which means that the photo must be thoroughly selected for its quality and be representative.  We still need to see how to make the photo upload possible through the TD current workflow  and sustainable across the TD versions. At the moment we ask to put the URL to the photo in the TD. We need guidelines on how to select the reference photo or schema (there are very nice schemas in the descriptors booklets published by Bioversity). Shall we just add a new variable called ' bunch shape photograph' where the URL to the photo will be stored in the TD?
2. However, I understand that you are referring to the photos collected through the fieldbook apps by numbers during trials on many plants that will support the analysis about the trait expression and the off-type. Then the fieldbook apps should upload in the Database the photos with proper metadata providing a good description of the traits and symptoms observed on the photos? with the variables ID or name in the database, isn't it? You need a good photo annotation process there.

**Comment by marieALaporte** [comment]
I think there are 2 different things here (I won't discuss about the reference photos that Elizabeth mentioned, as they can be added as xref):
- the photo description itself
- the traits that can be deduced from the photo

A possible solution could be to :
- create a new Trait Class for the photos (something like « photo type »). Each type of photos would then be described using the CO model Trait-Method-Scale-Variable.
	For instance,  "Bunch at harvest photograph » would be the Trait, the photo type would be the Trait Class, the way the picture must be taken (criteria like light or frame) can be part of the method, the scale could be the format of the photo. And the variable could then be the concatenation of the 3 (T-M-S)
		
- create a new variable that will use a calculation on the photo to obtain a trait value. 
	for instance, Bunch size could have a new method « calculation from a bunch photo » 

By doing so, you will then get a CO ID to annotate the photo itself (its type) and one (or more) ID to annotate the value of the traits that you can derive from the photo.

**Comment by bellerbrock** [comment]
Ok, looks like there has already been a lot of thinking about this! And right, in this case I'm not referring to photos illustrating a trait - it's sounds like there is already support for adding those as xrefs. 

Marie, your solution makes a lot of sense to me. With sweetpotato I think NCSU takes two or three photos per plot, one of a cut root showing flesh color and another showing a representative sample of roots and their shapes. Right now these photos are just used for spot checking/reference. But it'd be a big help to have them as formally defined photo traits in the ontology, and to include defined methods(instructions for taking them) and scales(photo format). That way it will be a much cleaner process to start using them in the calculation/derivation of other traits.

**Comment by elizabetharnaud** [comment]
Thanks for the additional information. 
So you need to have 'photo traits'  for reference field photos to illustrate your 3/4 traits.
For Banana, we have a series of minimum photos to be taken to differentiate the varieties. The guidelines for taking good photos of Musa plant parts  is a several-page document ( how to present the plant part, what distance, when to put a ruler  or a colour chart beside, dark background,  exposition, taking note of the camera making, etc…). A reference photo of excellent quality could be provided. So the method you mention that would be attached to the 'photo variable' in the TD to take the picture should be short description, perhaps including the plant stage of development,  that helps in the field book  but giving the reference to your guidelines if you have any? This would support a good calculation or derivation of traits.

**Comment by jaiswalp** [comment]
I prefer taking the method (photograph-based) out of the trait name. They should go to CO_methods. Otherwise as we pile on the high throughput method driven traits, we will end up with so many siblings. e.g. lidar-based plant height, photograph-based plant height, visually (eyeballed)-scored plant height, physically measured-using a scale plant height.

So think about it before going this route.

**Comment by bellerbrock** [comment]
Ah, I'm not sure how I missed this, but it looks like some of what we've been discussing has already been added to the sweetpotato ontology! There are 5 `Appearance of` traits with the method `Taking standardized photo` in the morphological trait class. And even a derived trait `Color of leave` (leaf? leaves?) where the method is `Color of leave picture`. 

There are problems with the implementation - it looks like a bunch of trait names have been attached to the wrong characteristics and scales. But we can use the `Appearance of roots` trait to at least get started!
