### ISSUE TITLE
Test Trait 1

### ISSUE THREAD

**Issue by dauglyon** [Planteome/ibp-sweetpotato-traits#16]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | David     |
| **Program** | BTI |

## Request

|                    |                         |
| ------------------ | ----------------------- |
| **Trait Name**         | Test Trait 1  |
| **Class**             | Morphological |
| **Definition**         | This is a test description   |
| **Measurement Method** | tested it.      |
| **Measurement Type**   | Categorical  |

#### Categories

| ID       | Description |
| -------- | ----------- |
| **A** | desc1    |
| **2** | desc2    |
| **3** | desc3    |

**Comment by nmenda** [comment]
test test
