### ISSUE TITLE
Best way to handle the same biochemicals traits measured at multiple time points?

### ISSUE THREAD

**Issue by bellerbrock** [Planteome/ibp-sweetpotato-traits#2]
The sweetpotato program at NCSU, as well as programs in Ghana and Uganda, is using NIRS to measure the new biochemical traits recently added to the ontology (Amylose, Anthocyanin, etc). But these traits aren't just measured once, they're done first on green samples, then cured samples, then at 6 weeks, 12 weeks, and so on. What is the best way of handling these measurements? There's interest in storing and analyzing them as separate measurements, but also in calculating an overall value for each compound.

**Comment by elizabetharnaud** [comment]
The time series and sub-sampling were discussed during the PhenoHarmonIS workshop and was perceived as database model elements more than  ontology concepts. However, Trushar and I are planning to push the discussion further so we enable a smooth exchange between the crop ontology variables and the fieldbook, where time series need to be recorded. We should share this discussion with him.

**Comment by bellerbrock** [comment]
Got it, thanks Elizabeth.

We have since addressed this issue as suggested, at the database level. We added [a tool](https://sweetpotatobase.org/tools/compose) that lets users combine traits with a time term, and then store those new traits in a composed traits ontology. The composed traits can then be searched, downloaded, and used in the fieldbook just like normal traits.
