### ISSUE TITLE
Keep/Drop trait

### ISSUE THREAD

**Issue by bellerbrock** [Planteome/ibp-sweetpotato-traits#3]
I don't see a trait for this yet in the ontology, but the NCSU program uses a boolean trait they call KEEP?DROP in their fieldbooks in the early stages of the breeding process. This trait is recorded first, and for most genotypes that are dropped it is not worth recording values for the remaining traits.

**Comment by jaiswalp** [comment]
Great one. But it seems that if selected for DROP value, all of the traits previously planned for scoring in the given study are not scored. Right? If yes, then it is not the trait inherent in the plant or population. This trait belongs to the individual experiment and not the plant.

**Comment by bellerbrock** [comment]
Right, in most cases the remaining traits planned for scoring are not scored. I see what you're saying in terms of belonging to the experiment, basically it's a selection decision based on a given experiment's selection criteria. 
Maybe this is outside the scope of the ontology, but can still be handled like a trait in the database and fieldbook.

**Comment by jaiswalp** [comment]
> Maybe this is outside the scope of the ontology, but can still be handled like a trait in the database and fieldbook. 

I think so. It is a metadata aspect of your experiment. The TO is for traits inherent to plant/plant-part/population

**Comment by bellerbrock** [comment]
Ok, then that's how we'll plan to handle it. Thanks for the clarification!
