### ISSUE TITLE
Storage Root Defects CO_331:0000423 needs to be re-worked

### ISSUE THREAD

**Issue by bellerbrock** [Planteome/ibp-sweetpotato-traits#4]
An abiotic stress trait called Storage Root Defects was added in the most recent version of the ontology. It's a categorical trait on a 14pt scale. Each category represents a different type of defect (Blisters (B), Sprouts (SPR), etc).

We've encountered a few problems with this setup. Defining the trait this way only allows you to select one defect, even though there are often multiple defects. And the 14pt scale is too large for the fieldbook app - any more than 12 categories causes it to crash. 

This system also overlaps in strange ways with other traits. It's classified as an abiotic stress trait, but Category 8 is for insect damages, a biotic stress trait. And existing traits classified as Agronomic ( CO_331:0000097 Storage root cracking) and Morphological ( CO_331:0000326 Storage Root Surface Defects ) already cover many of the same defects.

**Comment by bellerbrock** [comment]
An update from NSCU - they are now using 3 traits, called Storage Root Defects 1, Storage Root Defects 2, and Storage Root Defects 3. They've reduced the scale to 12 categories, and are selecting a different defect for each one, starting with the most severe defect for Storage Root Defects 1.

To reflect this in the ontology, they suggested adding something like Storage Root Defect (primary) and Storage Root Defect (secondary). Maybe even Storage Root Defect (tertiary). And reducing the scale to 12. This system has problems too though, because the resulting information is hard to analyze. Another solution they've discussed is having a separate trait for each possible defect, like the individual trait for  Storage root cracking. It's on a 4pt scale, with Category 0 = Absent, Category 3 = Few cracks, Category 5 = Medium number of cracks, Category 7 = Many cracks.

Having a measurement for each indivudal defect would tell something about severity as well as presence/absence, but could slow down the phenotyping workflow unless changes are made to the fieldbook app.

**Comment by bellerbrock** [comment]
another comment: the abbreviations need to be standardized . Blisters (B) conlficts with Bumpy(B). A good solution would be to create 3 letter abbreviations for all.

**Comment by bellerbrock** [comment]
Another note. Additional categories that have been requested:

Misshapes
Secondary roots
Tight hills
Deep eyes

**Comment by jaiswalp** [comment]
@elizabetharnaud @marieALaporte @cooperl09  Please check.
@bellerbrock can we call it 'root tuber' instead of 'storage root'. or at least as synonym. In fact  we need to be careful because in generic sense carrot and radish also have storage roots but they are essentially primary toots. Sweet potato root tubers are likely lateral roots. Please confirm.

**Comment by elizabetharnaud** [comment]
We have seen the post and it is already on our list of actions with Marie and I.

**Comment by bellerbrock** [comment]
addressed in sweetpotatobase working obo file with commit cb61c0c5658af21ca947cdc47e847aff23670c24
