### ISSUE TITLE
obo file formatting problems

### ISSUE THREAD

**Issue by bellerbrock** [Planteome/ibp-sweetpotato-traits#5]
##### format of traits and variables in cropontology.org obo download (http://www.cropontology.org/obo/CO_331):

[Term]
id: CO_331:0000069
name: Storage Root Shape (primary)
namespace: Sweet PotatoTrait
def: "undefined" []
namespace: Sweet PotatoScale
relationship: scale_of CO_331:Morphological%20trait

[Term]
id: CO_331:0000774
name: RtShpP_Et_1to8
synonym: "RTSHP1" EXACT []
namespace: SweetpotatoVariable
relationship: variable_of CO_331:0000069
##### format needed for sweetpotatobase (and other sgn databases):

[Term]
id: CO_331:0000069
name: Storage Root Shape (primary)
namespace: SweetpotatoTrait
def: "Storage Root Shape described from longitudinal sections made about the middle of freshly harvested storage roots" [Huaman1991:Def_4.2.1]
comment: | Entity: Root | Attribute: Shape | Trait status: Recommended.
synonym: "RtShpP" EXACT []
is_a: CO_331:0000002 ! Morphological trait

[Term]
id: CO_331:0000774
name: Storage Root Shape primary estimating 1-8
namespace: SweetpotatoTrait
def: "Storage Root Shape described from longitudinal sections made about the middle of freshly harvested storage roots" [Huaman1991:Def_4.2.1]
synonym: "RTSHP1" EXACT []
synonym: "RtShpP_Et_1to8" EXACT []
relationship: variable_of CO_331:0000069 ! Storage Root Shape (primary)

**Comment by marieALaporte** [comment]
You are right, something is going wrong with output from the website. I will work on that next week. 
Thanks !

**Comment by bellerbrock** [comment]
@marieALaporte great, thanks! Updating the .obo output format would be a big help, and not just for sweetpotatobase.

Also, is there any procedure in place for small fixes to the ontology displayed on cropontology.org? 

I've come across a few miss-spellings and misplaced characteristics. For example the morphological trait
`Storage Root Attachement ` is spelled wrong, and the biochemical trait `Asparagine content` has an incorrect trait description - it's displaying the description for `Peonidin content`.

**Comment by marieALaporte** [comment]
@bellerbrock I am closing the issue as I think this has been resolved. Reopen it if it is not.
