### ISSUE TITLE
Starch content of cooked roots in percent

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/ibp-sweetpotato-traits#57]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Jolien Swanckaert    |
| **Program** | CIP Ghana |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Starch content of cooked roots in percent    |
| **Definition**         | Percentage starch of cooked roots on a dry weight basis     |
| **Trait Class**        | Quality   |
| **Measurement Method** | NIRS prediction from calibration derived from standard laboratory analysis after cooking the roots        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | %           |

**Comment by jswancka** [comment]
@bellerbrock @dgemenet 
Is someone thinking about putting the cooked traits in the ontology? We, in Ghana, have a lot of data pending on cooked analysis that should go into sweetpotatobase.

**Comment by dgemenet** [comment]
Dear Joliene,
As these will be new traits, to avoid duplication in future, i suggest you make a list of traits and their descriptions according to CO in excel to share with the whole community to inform them that we are adding these traits as described.
