### ISSUE TITLE
Canopy Temperature

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/ibp-sweetpotato-traits#59]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Dorcus Gemenet    |
| **Program** | CIP |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Canopy Temperature    |
| **Definition**         | Measurement using an infrared thermometer on the canopy of a plot     |
| **Trait Class**        | Physiological   |
| **Measurement Method** | Measurement using an infrared thermometer on the canopy of a plot        |
| **Measurement Type**   | Unit |
| **Measurement Unit**   | 0C           |

**Comment by bellerbrock** [comment]
Also requested in #33.
