### ISSUE TITLE
Sweet potato storage root stalk trait is duplicated

### ISSUE THREAD

**Issue by cooperl09** [Planteome/ibp-sweetpotato-traits#68]
Currently there are two terms with the same name and def'n for this trait:

CO_331:0000342  sweetpotato storage root stalk trait- def'n: "Length of stalk joining the storage roots to the stems"

CO_331:0000410 sweetpotato storage root stalk trait- def'n: "Length of stalk joining the storage roots to the stems"

**Comment by bellerbrock** [comment]
Ok, I see the issue. They do seem to be the same trait, and even use the same scale. The one with id CO_331:0000342 has a few typos and has not been used in our database, so I'll remove that one.
