### ISSUE TITLE
Weight of storage root traits - definitions need to be clarified

### ISSUE THREAD

**Issue by cooperl09** [Planteome/ibp-sweetpotato-traits#69]
Both these have the same definition, but judging from the abbreviation, it looks like one is dry weight and one is fresh weight

id: CO_331:0000240
name: sweetpotato weight of storage root trait
def: "Weight of storage root samples" [CO:curators]
synonym: "RtFWt" EXACT []
is_a: TO:0000279 ! root weight

id: CO_331:0000244
name: sweetpotato weight of storage root trait
def: "Weight of storage root samples" [CO:curators]
synonym: "RtDWt" EXACT []

**Comment by dgemenet** [comment]
It seems CO-331:0000244  should be dry weight. They should be differentiated by introducing fresh and dry weight

**Comment by bellerbrock** [comment]
Good point Dorcus. I've fixed this in a branch and will make a pull request now if one of you could please give it your review! @cooperl09 @dgemenet
