### ISSUE TITLE
Agronomic trait 'yield of total roots' is duplicated

### ISSUE THREAD

**Issue by bellerbrock** [Planteome/ibp-sweetpotato-traits#9]
The ids, synonyms, and are Xrefs are different (`CO_331:0000082 RtYld  Grueneberg2010:Def_38` vs
`CO_331:0000309  RtYPP Grueneberg2016:Def_46` ) so I named the second one 'yield of total roots 2`  in our working file so I could at least load it.

But the defintion, method, and scale seem to be the same, maybe they should be merged instead?

**Comment by marieALaporte** [comment]
@dgemenet could please let us know what is the difference between those two traits?
I understand that one is measured during harvest and the other one after harvest. 
I believe there are the same trait and the harvest information can be handle maybe at the level of the method. What do you think?

**Comment by dgemenet** [comment]
Dear Marie,
You are right. That is the same trait.
Best regards
Dorcus

**Comment by marieALaporte** [comment]
@bellerbrock could you please obsolete the trait CO_331:0000309, the variable CO_331:0000681 and the method CO_331:0000898?

**Comment by bellerbrock** [comment]
No problem. @dgemenet thanks for clarifying!
